steps:
  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      [
        "-c",
        "docker pull us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/songsled-api:latest || exit 0",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/songsled-api:latest",
        "--cache-from",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/songsled-api:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/songsled-api:latest",
      ]
  # Deploy on cloud run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "songsled-api",
        "--image",
        us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/songsled-api:latest,
        --region,
        us-central1,
        --port,
        "8081",
        # --update-secrets=AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,
        # --update-secrets=AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest,
        # --update-secrets=PG_URI=PG_URI:latest,
      ]
  #  -update-secrets=ENV_VAR_NAME=SECRET_NAME:VERSION

timeout: 1800s
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/songsled-api:latest
