api:
  port: 8081
  host: localhost
  version: "1"

auth:
  jwt:
    issuer: songsled
    audience:
      - api

  oauth:
    google:
      userInfoUrl: https://www.googleapis.com/oauth2/v2/userinfo
      redirectUrl: http://localhost:8080/realms/master/broker/google/endpoint
      scopes:
        - https://www.googleapis.com/auth/userinfo.email
        - https://www.googleapis.com/auth/userinfo.profile

upload:
  region: northamerica-northeast1
  bucket: spume-musicproject
  encoder:
    logging: false
    enabled: false

repository:
  postgres:
    schema: database/schema.sql
    image: postgres:alpine

test:
  showErrorDetails: false
  loadTestdata: false
