services:
  server:
    container_name: server
    build: .
    ports:
      - 8081:8081

  site:
    container_name: site
    build: site
    ports:
      - 8080:80
  #db:
  # image: postgres:alpine
  #  ports:
  #  - 5432:5432
