

-- SELECT
-- songs.song_id,
-- song_artists,
-- -- song_genres,
-- streams,
-- duration,
-- songs.creation_date AS song_creation_date,  
-- -- albums.creation_date AS album_creation_date ,
-- -- albums.album_id,
-- -- albums.album_name,
-- song_cover_url, 	
-- song_url
-- FROM (SELECT string_agg(artists.artist_name, ', ') AS song_artists, song_id 
--     FROM artists
--     INNER JOIN artist_songs ON artist_songs.artist_id = artists.artist_id
--     WHERE artist_songs.artist_id='1928aca9-3f41-41a5-8103-8fb0c013aea0'
--     GROUP BY song_id) a1
-- INNER JOIN songs
-- ON (a1.song_id = songs.song_id)
--    (SELECT string_agg(genres.genre_name, ', ') AS song_genres, song_id
--     FROM genres
--     INNER JOIN song_genres ON genres.genre_id = song_genres.genre_id
-- 	WHERE song_genres.song_id='f7d84ef8-75dc-4331-b1e3-5ada0770c4c0'
--   	GROUP BY song_id) a2

-- INNER JOIN songs ON (songs.song_id = a1.song_id)
-- LEFT JOIN albums ON albums.album_id = a1.song_id
-- WHERE artists.artist_id='1928aca9-3f41-41a5-8103-8fb0c013aea0';
-- SELECT
-- songs.song_id,
-- artists,
-- genres,
-- streams,
-- duration,
-- songs.creation_date AS song_creation_date,  
-- albums.creation_date AS album_creation_date ,
-- albums.album_id,
-- albums.album_name,
-- song_cover_url, 	
-- song_url
-- FROM (SELECT string_agg(artists.artist_name, ', ') AS artists, song_id 
--     FROM artists
--     INNER JOIN artist_songs ON artist_songs.artist_id = artists.artist_id
--     WHERE artist_songs.song_id='f7d84ef8-75dc-4331-b1e3-5ada0770c4c0'
--     GROUP BY song_id) a1
-- INNER JOIN
--    (SELECT string_agg(genres.genre_name, ', ') AS genres, song_id
--     FROM genres
--     INNER JOIN song_genres ON genres.genre_id = song_genres.genre_id
-- 	WHERE song_genres.song_id='f7d84ef8-75dc-4331-b1e3-5ada0770c4c0'
--   	GROUP BY song_id) a2
-- ON (a1.song_id = a2.song_id)
-- INNER JOIN songs ON (songs.song_id = a1.song_id)
-- LEFT JOIN albums ON albums.album_id = a1.song_id