api:
  port: 8081
  host:
  jwt:
    accessKey: test
    refreshKey:

repository:
  type: postgres
  url:

oauth:
  google:
    clientId:
    clientSecret:
    redirectUrl:
    scopes:
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
