api:
  port: 8081
  host:
  version: "1.23"
  jwt:
    accessKey: test
    refreshKey:
    issuer: okapi

repository:
  type: dev
  url:

oauth:
  google:
    clientId:
    clientSecret:
    redirectUrl:
    scopes:
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
