api:
  port: 8081
  host: localhost
  version: "1"

services:
  auth:
    jwt:
      issuer: spume
      audience:
        - api
    oauth:
      google:
        redirectUrl: http://localhost:8081/v1/auth/google/redirect
        scopes:
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile
  encoder:
    logging: false

middleware:
  logger: false
  ratelimit: false

repository:
  postgres:
    image: postgres:alpine

aws:
  s3:
    bucket:
