api:
  port: 8081
  host: localhost
  version: "1"

services:
  auth:
    jwt:
      accessKey: ...
      refreshKey: ...
      issuer: okapi
    oauth:
      google:
        clientID: ...
        clientSecret: ...
        redirectURL: http://localhost:8081/v1/auth/google/redirect
        scopes:
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile
  smtp:
    host: ...
    port: ...
    email: ...
    password: ...

middleware:
  ratelimit: true

repository:
  postgres:
    image: postgres:alpine
    username: postgres
    password: ...
    host: localhost
    database: musicproject

aws:
