api:
  port: 8081
  host: localhost
  version: "1"

services:
  auth:
    jwt:
      issuer: okapi
    oauth:
      google:
        redirectUrl: http://localhost:8081/v1/auth/google/redirect
        scopes:
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile

middleware:
  logger: false
  ratelimit: false

repository:
  postgres:
    image: postgres:alpine

aws:
  s3:
    buckets:
      audio: okapi-audio-634220481321-ca-central-1-an
      log: d
