// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Album struct {
	AlbumID       uuid.UUID
	AlbumName     string
	AlbumCoverUrl sql.NullString
	CreationDate  string
}

type AlbumArtist struct {
	AlbumID  uuid.UUID
	ArtistID uuid.UUID
}

type Artist struct {
	ArtistID        uuid.UUID
	ArtistName      string
	ArtistAvatarUrl sql.NullString
}

type ArtistSong struct {
	ArtistID uuid.UUID
	SongID   uuid.UUID
}

type Genre struct {
	GenreID   uuid.UUID
	GenreName string
}

type Playlist struct {
	PlaylistID       uuid.UUID
	UserID           uuid.NullUUID
	PlaylistCoverUrl sql.NullString
	PlaylistName     string
}

type PlaylistSong struct {
	PlaylistID uuid.UUID
	SongID     uuid.UUID
}

type Song struct {
	SongID       uuid.UUID
	SongName     string
	Streams      int32
	Duration     int32
	CreationDate string
	AlbumID      uuid.NullUUID
	SongCoverUrl sql.NullString
	SongAudioUrl string
}

type SongGenre struct {
	GenreID uuid.UUID
	SongID  uuid.UUID
}

type SongRating struct {
	UserID      uuid.NullUUID
	SongID      uuid.UUID
	RatingValue int32
}
