// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Album struct {
	AlbumID      uuid.UUID
	AlbumName    sql.NullString
	CreationDate sql.NullString
	ArtistID     uuid.NullUUID
	GenreID      uuid.NullUUID
}

type AlbumArtist struct {
	AlbumID  uuid.UUID
	ArtistID uuid.UUID
}

type Artist struct {
	ArtistID   uuid.UUID
	ArtistName string
}

type ArtistSong struct {
	ArtistID uuid.NullUUID
	SongID   uuid.NullUUID
}

type Genre struct {
	GenreID uuid.UUID
	Genre   string
}

type Playlist struct {
	PlaylistID   uuid.UUID
	UserID       uuid.NullUUID
	PlaylistName string
}

type PlaylistSong struct {
	PlaylistID uuid.UUID
	SongID     uuid.UUID
}

type Song struct {
	SongID       uuid.UUID
	SongName     string
	Streams      int32
	Duration     int32
	CreationDate string
	AlbumID      uuid.NullUUID
	SongImage    sql.NullString
	SongUrl      string
}

type SongGenre struct {
	GenreID uuid.UUID
	SongID  uuid.UUID
}

type SongRating struct {
	UserID      uuid.NullUUID
	SongID      uuid.UUID
	RatingValue int32
}
