// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Album struct {
	AlbumID      uuid.UUID
	ArtistID     uuid.NullUUID
	AlbumName    sql.NullString
	GenreID      uuid.NullUUID
	CreationDate sql.NullString
}

type Artist struct {
	ArtistID   uuid.UUID
	ArtistName sql.NullString
}

type Genre struct {
	GenreID uuid.UUID
	Genre   sql.NullString
}

type Playlist struct {
	PlaylistID   uuid.UUID
	UserID       uuid.UUID
	PlaylistName string
}

type PlaylistSong struct {
	PlaylistID uuid.UUID
	SongID     uuid.UUID
}

type Song struct {
	SongID       uuid.UUID
	AlbumID      uuid.NullUUID
	SongName     string
	Streams      int32
	Duration     int32
	CreationDate string
	SongImage    sql.NullString
	SongUrl      string
}

type SongRating struct {
	UserID      uuid.UUID
	SongID      uuid.UUID
	RatingValue int32
}

type User struct {
	UserID       uuid.UUID
	Email        string
	PasswordHash sql.NullString
	CreatedAt    time.Time
	AvatarUrl    sql.NullString
}

type UserRole struct {
	UserID   uuid.NullUUID
	RoleName sql.NullString
}
