// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package gensqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteSongByID = `-- name: DeleteSongByID :exec
DELETE FROM songs WHERE song_id=$1
`

func (q *Queries) DeleteSongByID(ctx context.Context, songID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSongByID, songID)
	return err
}

const getAggregatedRating = `-- name: GetAggregatedRating :one
SELECT SUM(rating_value) / COUNT(rating_value)
FROM song_ratings 
WHERE song_id=$1
`

func (q *Queries) GetAggregatedRating(ctx context.Context, songID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAggregatedRating, songID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :many
SELECT 
    playlists.user_id,
    playlists.playlist_name,
    playlist_songs.playlist_id,
    songs.song_name, 
    songs.streams,
	songs.duration, 
    songs.creation_date,
    songs.song_image,
    songs.song_url
FROM songs
INNER JOIN playlist_songs ON playlist_songs.song_id = songs.song_id
INNER JOIN playlists ON playlists.playlist_id = playlist_songs.playlist_id
INNER JOIN genres ON genres.genre_id = song_genres.genre_id
WHERE playlist_songs.playlist_id=$1
`

type GetPlaylistByIDRow struct {
	UserID       uuid.NullUUID
	PlaylistName string
	PlaylistID   uuid.UUID
	SongName     string
	Streams      int32
	Duration     int32
	CreationDate string
	SongImage    sql.NullString
	SongUrl      string
}

func (q *Queries) GetPlaylistByID(ctx context.Context, playlistID uuid.UUID) ([]GetPlaylistByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistByID, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaylistByIDRow
	for rows.Next() {
		var i GetPlaylistByIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.PlaylistName,
			&i.PlaylistID,
			&i.SongName,
			&i.Streams,
			&i.Duration,
			&i.CreationDate,
			&i.SongImage,
			&i.SongUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistSongs = `-- name: GetPlaylistSongs :many
SELECT playlist_id, user_id, playlist_name FROM playlists
WHERE playlist_id=$1
`

func (q *Queries) GetPlaylistSongs(ctx context.Context, playlistID uuid.UUID) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistSongs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(&i.PlaylistID, &i.UserID, &i.PlaylistName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongByID = `-- name: GetSongByID :one
SELECT song_id, song_name, streams, duration, creation_date, album_id, song_image, song_url FROM songs
WHERE song_id=$1
`

func (q *Queries) GetSongByID(ctx context.Context, songID uuid.UUID) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongByID, songID)
	var i Song
	err := row.Scan(
		&i.SongID,
		&i.SongName,
		&i.Streams,
		&i.Duration,
		&i.CreationDate,
		&i.AlbumID,
		&i.SongImage,
		&i.SongUrl,
	)
	return i, err
}

const getSongRandom = `-- name: GetSongRandom :many
SELECT song_id, song_name, streams, duration, creation_date, album_id, song_image, song_url FROM songs 
ORDER BY RANDOM() LIMIT $1
`

func (q *Queries) GetSongRandom(ctx context.Context, limit int32) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, getSongRandom, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.SongID,
			&i.SongName,
			&i.Streams,
			&i.Duration,
			&i.CreationDate,
			&i.AlbumID,
			&i.SongImage,
			&i.SongUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putPlaylist = `-- name: PutPlaylist :one






INSERT INTO playlists
(user_id)
VALUES($1) RETURNING playlist_id
`

// INNER JOIN playlists ON playlists.playlist_id = playlist_songs.playlist_id
// INNER JOIN genres ON genres.genre_id = song_genres.genre_id
func (q *Queries) PutPlaylist(ctx context.Context, userID uuid.NullUUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, putPlaylist, userID)
	var playlist_id uuid.UUID
	err := row.Scan(&playlist_id)
	return playlist_id, err
}

const putPlaylistSong = `-- name: PutPlaylistSong :exec
INSERT INTO playlist_songs
(playlist_id, song_id)
VALUES($1, $2)
`

type PutPlaylistSongParams struct {
	PlaylistID uuid.UUID
	SongID     uuid.UUID
}

func (q *Queries) PutPlaylistSong(ctx context.Context, arg PutPlaylistSongParams) error {
	_, err := q.db.ExecContext(ctx, putPlaylistSong, arg.PlaylistID, arg.SongID)
	return err
}

const putRating = `-- name: PutRating :exec
INSERT INTO song_ratings 
(song_id, user_id, rating_value) 
VALUES($1, $2, $3)
`

type PutRatingParams struct {
	SongID      uuid.UUID
	UserID      uuid.NullUUID
	RatingValue int32
}

func (q *Queries) PutRating(ctx context.Context, arg PutRatingParams) error {
	_, err := q.db.ExecContext(ctx, putRating, arg.SongID, arg.UserID, arg.RatingValue)
	return err
}

const putSong = `-- name: PutSong :one
INSERT INTO songs
(album_id, song_name, streams, duration, creation_date)
VALUES($1, $2, $3, $4, $5) RETURNING song_id
`

type PutSongParams struct {
	AlbumID      uuid.NullUUID
	SongName     string
	Streams      int32
	Duration     int32
	CreationDate string
}

func (q *Queries) PutSong(ctx context.Context, arg PutSongParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, putSong,
		arg.AlbumID,
		arg.SongName,
		arg.Streams,
		arg.Duration,
		arg.CreationDate,
	)
	var song_id uuid.UUID
	err := row.Scan(&song_id)
	return song_id, err
}
